# Generated by Django 4.2.3 on 2023-07-27 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spotlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
                ('image1', models.FileField(blank=True, null=True, upload_to='images/')),
                ('body1', models.TextField(blank=True, null=True)),
                ('image2', models.FileField(blank=True, null=True, upload_to='images/')),
                ('body2', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
                ('blogs', models.CharField(max_length=2000, unique=True)),
                ('read_time', models.CharField(max_length=100)),
                ('image1', models.FileField(blank=True, null=True, upload_to='images/')),
                ('body1', models.TextField(blank=True, null=True)),
                ('image2', models.FileField(blank=True, null=True, upload_to='images/')),
                ('body2', models.TextField(blank=True, null=True)),
                ('image3', models.FileField(blank=True, null=True, upload_to='images/')),
                ('body3', models.TextField(blank=True, null=True)),
                ('image4', models.FileField(blank=True, null=True, upload_to='images/')),
                ('body4', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('post', models.BooleanField(default=False)),
                ('post_published', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='blog.category')),
            ],
        ),
    ]
