# Generated by Django 4.2.3 on 2023-08-06 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blogs',
            new_name='slug',
        ),
    ]
